import {describe,expect,test} from "bun:test";
import {mkdtemp,rm,writeFile} from "node:fs/promises"; import {tmpdir} from "node:os"; import {join} from "node:path";
import {SessionManager} from "@earendil-works/pi-coding-agent";
import {GoalStore,latestGoal,GOAL_ENTRY_TYPE} from "../src/goals/store";
import {GoalContinuationController,MAX_NO_PROGRESS_CONTINUATIONS} from "../src/goals/controller";
import {registerGoalMode} from "../src/goals/extension";
const input={objective:"Ship goal mode",criteria:["tests pass","state persists"],constraints:["no installs"]};
describe("goal durable state",()=>{test("requires explicit fields and replays append-only JSONL entries",()=>{const entries:any[]=[];let tick=0;const store=new GoalStore((customType,data)=>entries.push({type:"custom",customType,data}),[],()=>"t"+(++tick));expect(()=>store.set({...input,criteria:[]})).toThrow("criteria is required");const active=store.set(input);expect(active).toMatchObject({...input,status:"active",revision:1});expect(latestGoal(entries)).toEqual(active);expect(()=>store.update({status:"completed"})).toThrow("completion evidence");expect(()=>store.update({status:"blocked"})).toThrow("blocker explanation");const done=store.update({status:"completed",evidence:"bun test: 42 pass"});expect(new GoalStore(()=>{},entries).get()).toEqual(done);store.clear();expect(latestGoal(entries)).toBeUndefined();expect(entries.every(e=>e.customType===GOAL_ENTRY_TYPE)).toBe(true)});
test("waiting accepts only currently owned running jobs",()=>{const store=new GoalStore(()=>{});store.set(input);expect(()=>store.update({status:"waiting",pendingJobIds:["foreign"]},new Set(["mine"]))).toThrow("owned");expect(store.update({status:"waiting",pendingJobIds:["mine"]},new Set(["mine"]))).toMatchObject({status:"waiting",pendingJobIds:["mine"]})});});
test("no-progress continuation is bounded and real work resets it",()=>{const c=new GoalContinuationController();const goal:any={status:"active",revision:1};expect(c.settle(goal,false)).toBe("continue");c.markAutomaticStart(goal);for(let i=1;i<MAX_NO_PROGRESS_CONTINUATIONS;i++)expect(c.settle(goal,false)).toBe("continue");expect(c.settle(goal,false)).toBe("pause");c.markAutomaticStart(goal);expect(c.settle(goal,true)).toBe("continue")});
function harness(entries:any[]=[]){const handlers:Record<string,Function[]>= {},commands:Record<string,any>={},sent:string[]=[],notices:any[]=[],appended:any[]=[];const pi:any={on(n:string,h:Function){(handlers[n]??=[]).push(h)},registerCommand(n:string,o:any){commands[n]=o},appendEntry(customType:string,data:any){appended.push({type:"custom",customType,data})},sendUserMessage(m:string){sent.push(m)}};const runtime=registerGoalMode(pi,()=>new Set(["job_1"]));const ctx:any={sessionManager:{getEntries:()=>entries},ui:{notify:(...a:any[])=>notices.push(a)},hasPendingMessages:()=>false,isIdle:()=>false};handlers.session_start[0]({},ctx);return{handlers,commands,sent,notices,appended,runtime,ctx}}
test("agent helper validates terminal states and only active settles continue",()=>{const h=harness();h.runtime.handle("goal.set",input);expect(()=>h.runtime.handle("goal.update",{status:"completed"})).toThrow();h.handlers.agent_settled[0]({},h.ctx);expect(h.sent).toHaveLength(1);expect(h.sent[0]).toContain("Ship goal mode");expect(h.sent[0]).toContain("- tests pass");h.runtime.handle("goal.update",{status:"waiting",pendingJobIds:["job_1"]});h.handlers.agent_settled[0]({},h.ctx);expect(h.sent).toHaveLength(1)});
test("queued input and interruption pause before continuation",()=>{const h=harness();h.runtime.handle("goal.set",input);h.ctx.hasPendingMessages=()=>true;h.handlers.agent_settled[0]({},h.ctx);expect(h.runtime.get()).toMatchObject({status:"paused",pauseReason:"Paused for queued user input"});expect(h.sent).toHaveLength(0);h.commands.goal.handler("resume",h.ctx);h.handlers.input[0]({source:"interactive",streamingBehavior:"steer"},h.ctx);expect(h.runtime.get()?.status).toBe("paused")});
test("slash command sets explicit structured goal and resume survives replay",async()=>{const h=harness();await h.commands.goal.handler("set Build it --criteria one; two --constraints stay offline",h.ctx);expect(h.runtime.get()).toMatchObject({objective:"Build it",criteria:["one","two"],constraints:["stay offline"]});expect(h.sent.at(-1)).toContain("Objective: Build it");await h.commands.goal.handler("",h.ctx);expect(h.notices.at(-1)[0]).toContain("Status: active");const resumed=harness(h.appended);expect(resumed.runtime.get()).toMatchObject({objective:"Build it",status:"active"})});

test("goal history is durable JSONL across reopen and compaction entries",async()=>{const dir=await mkdtemp(join(tmpdir(),"die-goal-jsonl-"));try{let manager=SessionManager.create(dir,join(dir,"sessions"));const initialFile=manager.getSessionFile()!;await writeFile(initialFile,JSON.stringify(manager.getHeader())+"\n",{flag:"wx"});manager=SessionManager.open(initialFile);manager.appendMessage({role:"user",content:"start",timestamp:1});const store=new GoalStore((type,data)=>manager.appendCustomEntry(type,data));store.set(input);const file=manager.getSessionFile()!;manager=SessionManager.open(file);const before=latestGoal(manager.getEntries());expect(before?.objective).toBe(input.objective);const id=(manager.getEntries().find((e:any)=>e.type==="message") as any).id;manager.appendCompaction("summary",id,100,{strategy:"test"});manager=SessionManager.open(file);expect(latestGoal(manager.getEntries())).toEqual(before);expect((await Bun.file(file).text()).trim().split("\n").every(line=>{JSON.parse(line);return true})).toBe(true)}finally{await rm(dir,{recursive:true,force:true})}});
