import type { ExtensionAPI, ExtensionContext } from "@earendil-works/pi-coding-agent";
import goalContinuation from "../prompts/goal-continuation.md" with { type: "text" };
import { GoalContinuationController } from "./controller";
import { GoalStore } from "./store";
import type { GoalState } from "./types";
export interface GoalRuntime { get():GoalState|undefined; handle(method:string,params:unknown):unknown }
const format=(g?:GoalState)=>g?["Goal: "+g.objective,"Status: "+g.status,"Criteria: "+g.criteria.join("; "),"Constraints: "+(g.constraints.join("; ")||"none"),g.evidence&&"Evidence: "+g.evidence,g.blocker&&"Blocker: "+g.blocker,g.pendingJobIds?.length&&"Waiting on: "+g.pendingJobIds.join(", "),g.pauseReason&&"Reason: "+g.pauseReason].filter(Boolean).join("\n"):"No goal is set.";
function continuation(goal:GoalState){return goalContinuation.trimEnd().replace("{{objective}}",goal.objective).replace("{{criteria}}",goal.criteria.map(x=>"- "+x).join("\n")).replace("{{constraints}}",goal.constraints.length?goal.constraints.map(x=>"- "+x).join("\n"):"- None")}
function parseSet(args:string){const c=args.indexOf(" --criteria "),k=args.indexOf(" --constraints ");if(c<=0||k<=c)throw new Error("Usage: /goal set <objective> --criteria <criterion[;...]> --constraints <constraint[;...]>");const split=(v:string)=>v.split(";").map(x=>x.trim()).filter(Boolean);return{objective:args.slice(0,c).trim(),criteria:split(args.slice(c+12,k)),constraints:split(args.slice(k+15))}}
export function registerGoalMode(pi:ExtensionAPI,runningJobIds:()=>ReadonlySet<string>):GoalRuntime{
 let store:GoalStore|undefined,context:ExtensionContext|undefined,work=false;const controller=new GoalContinuationController();const ensureStore=(ctx:ExtensionContext)=>{context=ctx;store??=new GoalStore((type,data)=>pi.appendEntry(type,data),ctx.sessionManager?.getEntries()??[])};const requireStore=()=>{if(!store)throw new Error("Goal state is not initialized");return store};const notify=(m:string,l:"info"|"warning"="info")=>context?.ui.notify(m,l);const pause=(reason:string)=>{const current=store?.get();if(current?.status==="active")store!.update({status:"paused",reason})};
 pi.registerCommand("goal",{description:"Set or inspect persistent goal mode",async handler(args,ctx){context=ctx;const parts=args.trim()?args.trim().split(/\s+/):["status"],command=parts[0]!,value=parts.slice(1).join(" ");try{if(command==="set")requireStore().set(parseSet(value));else if(command==="status"){notify(format(requireStore().get()));return}else if(command==="pause")requireStore().update({status:"paused",reason:value||"Paused by user"});else if(command==="resume")requireStore().update({status:"active"});else if(command==="clear")requireStore().clear();else throw new Error("Usage: /goal set|status|pause|resume|clear");controller.reset();const current=requireStore().get();notify(format(current));if(current?.status==="active"&&(command==="set"||command==="resume")){controller.markAutomaticStart(current);pi.sendUserMessage(continuation(current),{deliverAs:"followUp"})}}catch(e){notify(e instanceof Error?e.message:String(e),"warning")}}});
 pi.on("session_start",(_e,ctx)=>{context=ctx;store=new GoalStore((type,data)=>pi.appendEntry(type,data),ctx.sessionManager?.getEntries()??[]);controller.reset()});
 pi.on("before_agent_start",(_e,ctx)=>ensureStore(ctx));
 pi.on("input",(e,ctx)=>{if(e.source!=="extension"&&e.streamingBehavior!==undefined)pause("Paused by user interruption")});
 pi.on("tool_execution_end",()=>{work=true});
 pi.on("agent_end",e=>{const last=[...e.messages].reverse().find(m=>m.role==="assistant");if(last?.stopReason==="aborted"||last?.stopReason==="error")pause("Paused after interrupted agent turn")});
 pi.on("agent_settled",(_e,ctx)=>{context=ctx;const goal=store?.get();if(!goal||goal.status!=="active"){work=false;controller.settle(goal,false);return}if(ctx.signal?.aborted){pause("Paused after interruption");work=false;return}if(ctx.hasPendingMessages()){pause("Paused for queued user input");work=false;return}const action=controller.settle(goal,work);work=false;if(action==="pause"){store!.update({status:"paused",reason:"Paused after repeated automatic turns made no meaningful progress"});notify("Goal paused: repeated continuations made no progress","warning");return}if(action==="continue"){const latest=store!.get()!;controller.markAutomaticStart(latest);pi.sendUserMessage(continuation(latest),{deliverAs:"followUp"})}});
 return{get:()=>store?.get(),handle(method,params){const input=(params&&typeof params==="object"?params:{}) as Record<string,unknown>;if(method==="goal.get")return requireStore().get()??null;if(method==="goal.set"){controller.reset();return requireStore().set({objective:input.objective,criteria:input.criteria,constraints:input.constraints})}if(method==="goal.update"){work=true;return requireStore().update(input as never,runningJobIds())}if(method==="goal.clear"){controller.reset();requireStore().clear();return{cleared:true}}throw new Error("Unknown goal method: "+method)}}
}
